/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.projeto.ong.view;

import com.projeto.ong.session.SessionManager;
import com.projeto.ong.util.JPAUtil;

/**
 *
 * @author aron.oliveira
 */
public class PrincipalView extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalView
     */
    public PrincipalView() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jdpprincipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuUsuario = new javax.swing.JMenuItem();
        jMenuProduto = new javax.swing.JMenuItem();
        jMenuOficina = new javax.swing.JMenuItem();
        jMenuPessoa = new javax.swing.JMenuItem();
        jMenuInscricao = new javax.swing.JMenuItem();
        jMenuDoacao = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Principal");
        setExtendedState(6);
        setSize(new java.awt.Dimension(800, 6));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        javax.swing.GroupLayout jdpprincipalLayout = new javax.swing.GroupLayout(jdpprincipal);
        jdpprincipal.setLayout(jdpprincipalLayout);
        jdpprincipalLayout.setHorizontalGroup(
            jdpprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 718, Short.MAX_VALUE)
        );
        jdpprincipalLayout.setVerticalGroup(
            jdpprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );

        jMenu1.setText("Cadastros");

        jMenuUsuario.setText("Usuário");
        jMenuUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuUsuarioActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuUsuario);

        jMenuProduto.setText("Produto");
        jMenuProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuProdutoActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuProduto);

        jMenuOficina.setText("Oficina");
        jMenuOficina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuOficinaActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuOficina);

        jMenuPessoa.setText("Pessoa");
        jMenuPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuPessoaActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuPessoa);

        jMenuInscricao.setText("Inscrição");
        jMenuInscricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuInscricaoActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuInscricao);

        jMenuDoacao.setText("Doação");
        jMenuDoacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuDoacaoActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuDoacao);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Consultas");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Relatórios");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Ajuda");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpprincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jdpprincipal)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        System.out.println("formWindowActivated");
        /* criando conexão com o SGBD */
        new Thread(() -> {
            JPAUtil.createEntityManagerFactory();
        }).start();
    }//GEN-LAST:event_formWindowActivated

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        System.out.println("formWindowOpened");
        if (SessionManager.getUsuarioLogado() == null) {
            LoginView login = new LoginView(this, true);
            login.setLocationRelativeTo(this);
            login.setVisible(true);
        }
    }//GEN-LAST:event_formWindowOpened

    private void jMenuUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuUsuarioActionPerformed
        UsuarioView janelaUsuario = new UsuarioView();
        janelaUsuario.setVisible(true);
    }//GEN-LAST:event_jMenuUsuarioActionPerformed

    private void jMenuInscricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuInscricaoActionPerformed

        InscricaoView janelaInscricao = new InscricaoView();
        janelaInscricao.setVisible(true);

    }//GEN-LAST:event_jMenuInscricaoActionPerformed

    private void jMenuDoacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuDoacaoActionPerformed
        DoacaoView janelaDoacao = new DoacaoView();
        janelaDoacao.setVisible(true);
    }//GEN-LAST:event_jMenuDoacaoActionPerformed

    private void jMenuProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuProdutoActionPerformed
        ManutencaoProdutoView janelaProduto = new ManutencaoProdutoView();
        janelaProduto.setVisible(true);
    }//GEN-LAST:event_jMenuProdutoActionPerformed

    private void jMenuOficinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuOficinaActionPerformed
        OficinaView janelaOficina = new OficinaView();
        janelaOficina.setVisible(true);
    }//GEN-LAST:event_jMenuOficinaActionPerformed

    private void jMenuPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuPessoaActionPerformed
        PessoaView janelaPessoa = new PessoaView();
        janelaPessoa.setVisible(true);
    }//GEN-LAST:event_jMenuPessoaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuDoacao;
    private javax.swing.JMenuItem jMenuInscricao;
    private javax.swing.JMenuItem jMenuOficina;
    private javax.swing.JMenuItem jMenuPessoa;
    private javax.swing.JMenuItem jMenuProduto;
    private javax.swing.JMenuItem jMenuUsuario;
    private javax.swing.JDesktopPane jdpprincipal;
    // End of variables declaration//GEN-END:variables

    /**
     *
     * @param args
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalView().setVisible(true);
            }
        });
    }

}
